spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    properties:
      username: ${KAFKA_USERNAME}
      password: ${KAFKA_PASSWORD}
      security:
        protocol: SASL_SSL
    sasl:
      mechanism: SCRAM-SHA-256

app:
  topic:
    orders-from-foundry: 82jesyk2-orders-from-foundry
    mass-to-foundry: 82jesyk2-mass-to-foundry
server:
  port: 8080

#logging:
#  level:
#    root: ERROR
#    org.springframework.web: ERROR
#    com.memorynotfound: DEBUG