spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: true


app:
  topic:
    orders-from-foundry: orders-from-foundry
    mass-to-foundry: mass-to-foundry
server:
  port: 8080

#logging:
#  level:
#    root: ERROR
#    org.springframework.web: ERROR
#    com.memorynotfound: DEBUG